# Generated by Django 5.2.3 on 2025-06-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meteo', '0002_alter_usuarioextendido_ciudad_favorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioextendido',
            name='idusuario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
